#ifndef __GHCAUTOCONF_H__
#define __GHCAUTOCONF_H__
#define ALIGNMENT_CHAR 1
#define ALIGNMENT_DOUBLE 8
#define ALIGNMENT_FLOAT 4
#define ALIGNMENT_INT 4
#define ALIGNMENT_LONG 8
#define ALIGNMENT_LONG_LONG 8
#define ALIGNMENT_SHORT 2
#define ALIGNMENT_UNSIGNED_CHAR 1
#define ALIGNMENT_UNSIGNED_INT 4
#define ALIGNMENT_UNSIGNED_LONG 8
#define ALIGNMENT_UNSIGNED_LONG_LONG 8
#define ALIGNMENT_UNSIGNED_SHORT 2
#define ALIGNMENT_VOID_P 8
#define CC_SUPPORTS_TLS 1
#define HAS_VISIBILITY_HIDDEN 1
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_BIN_SH 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CTIME_R 1
#define HAVE_CTYPE_H 1
#define HAVE_DECL_CTIME_R 1
#define HAVE_DIRENT_H 1
#define HAVE_DLFCN_H 1
#define HAVE_ERRNO_H 1
#define HAVE_EVENTFD 1
#define HAVE_FCNTL_H 1
#define HAVE_FORK 1
#define HAVE_GETRUSAGE 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_GRP_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIBDL 1
#define HAVE_LIBIBERTY 1
#define HAVE_LIBM 1
#define HAVE_LIBRT 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_LONG_LONG 1
#define HAVE_MEMORY_H 1
#define HAVE_PRINTF_LDBLSTUB 0
#define HAVE_PTHREAD_H 1
#define HAVE_PWD_H 1
#define HAVE_SCHED_H 1
#define HAVE_SCHED_SETAFFINITY 1
#define HAVE_SETITIMER 1
#define HAVE_SETLOCALE 1
#define HAVE_SIGINTERRUPT 1
#define HAVE_SIGNAL_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYSCONF 1
#define HAVE_SYS_EVENTFD_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIMEB_H 1
#define HAVE_SYS_TIMES_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_UTSNAME_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_TIMER_SETTIME 1
#define HAVE_TIMES 1
#define HAVE_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UTIME_H 1
#define HAVE_VFORK 1
#define HAVE_WORKING_FORK 1
#define HAVE_WORKING_VFORK 1
#define RETSIGTYPE void
#define SIZEOF_CHAR 1
#define SIZEOF_DOUBLE 8
#define SIZEOF_FLOAT 4
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_SHORT 2
#define SIZEOF_UNSIGNED_CHAR 1
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8
#define SIZEOF_UNSIGNED_SHORT 2
#define SIZEOF_VOID_P 8
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define USE_TIMER_CREATE 1
#define VOID_INT_SIGNALS 1
#ifdef AC_APPLE_UNIVERSAL_BUILD
#ifdef __BIG_ENDIAN__
#define WORDS_BIGENDIAN 1
#endif
#else
#ifndef WORDS_BIGENDIAN
#endif
#endif
#ifndef _DARWIN_USE_64_BIT_INODE
#define _DARWIN_USE_64_BIT_INODE 1
#endif
#define TABLES_NEXT_TO_CODE 1
#endif
